My Sample Features

My Sample - Features - My First Area
	My First Failing Feature
		My First Scenario [Failed]
			Given my step 1
			When my step 2 [Failed]
				Error Type: Exception
				   Message: My first exception.
				     Stack:    at MySample.Features.MyFirstArea.MyFirstFailingFeature.<>c.<MyFirstScenario>b__0_1(Step s) in C:\Users\stearm01\source\xBDD\MySample.Features\MyFirstArea\MyFirstFailingFeature.cs:line 24
				               at xBDD.Core.StepExecutor.<>c__DisplayClass4_0.<ExecuteStepAsync>b__0() in C:\Users\stearm01\source\xBDD\xBDD\Core\StepExecutor.cs:line 25
				               at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
				            --- End of stack trace from previous location where exception was thrown ---
				               at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
				            --- End of stack trace from previous location where exception was thrown ---
				               at xBDD.Core.StepExecutor.ExecuteStepAsync(Step step) in C:\Users\stearm01\source\xBDD\xBDD\Core\StepExecutor.cs:line 25
			Then my step 3 [Skipped - Previous Error]
